### ISSUE TITLE
Suggestion: libfcgi-bin depends on libfcgi0ldbl

### ISSUE THREAD

**Issue by Reiner030** [Jmeyering/php-fpm-cli#2]
... in Debian Jessie; so if you want to call ```cgi-fcgi``` you must have also setup it's library ?

And if you need a performant script you should better check a local path if the library or a self-made stamp file instead of checking in every call your package cache if it's installed?

Bests ;)

**Comment by Jmeyering** [comment]
Right now the library only supports Ubuntu. Although a PR to support Debian Jesse would be appreciated also.
